import { useRef, useCallback, useEffect, useState } from 'react';
import type { Workout } from '../../../types/workout';
import { Modal } from '../../../components/ui/Modal';

interface Props {
  workout: Workout | null;
  open: boolean;
  onClose: () => void;
}

export function SessionPoster({ workout, open, onClose }: Props) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [dataUrl, setDataUrl] = useState<string | null>(null);

  const drawPoster = useCallback(() => {
    if (!workout || !canvasRef.current) return;
    const canvas = canvasRef.current;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const W = 540;
    const H = 720;
    canvas.width = W;
    canvas.height = H;

    // Background
    ctx.fillStyle = '#080c09';
    ctx.fillRect(0, 0, W, H);

    // Border glow
    ctx.strokeStyle = '#2ecc71';
    ctx.lineWidth = 2;
    ctx.strokeRect(16, 16, W - 32, H - 32);

    // Header
    ctx.fillStyle = '#2ecc71';
    ctx.font = 'bold 36px "Bebas Neue", sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText('FORGE', W / 2, 60);

    ctx.fillStyle = '#8a8a8a';
    ctx.font = '14px "Barlow", sans-serif';
    ctx.fillText('SESSION COMPLETE', W / 2, 82);

    // Workout name
    ctx.fillStyle = '#e0e0e0';
    ctx.font = 'bold 22px "Barlow Condensed", sans-serif';
    ctx.fillText(workout.name, W / 2, 120);

    // Date
    ctx.fillStyle = '#8a8a8a';
    ctx.font = '13px "Barlow", sans-serif';
    ctx.fillText(
      new Date(workout.date).toLocaleDateString('en-US', {
        weekday: 'long',
        month: 'long',
        day: 'numeric',
        year: 'numeric',
      }),
      W / 2,
      142,
    );

    // Divider
    ctx.strokeStyle = '#1a2e1f';
    ctx.lineWidth = 1;
    ctx.beginPath();
    ctx.moveTo(40, 160);
    ctx.lineTo(W - 40, 160);
    ctx.stroke();

    // Stats grid
    const totalSets = workout.exercises.reduce((acc, ex) => acc + ex.sets.length, 0);
    const totalVolume = workout.exercises.reduce(
      (acc, ex) => acc + ex.sets.reduce((s, set) => s + set.reps * set.weight, 0),
      0,
    );
    const muscles = [...new Set(workout.exercises.map((e) => e.muscle))];

    const stats = [
      { label: 'Duration', value: `${workout.duration ?? 0} min` },
      { label: 'Exercises', value: String(workout.exercises.length) },
      { label: 'Total Sets', value: String(totalSets) },
      { label: 'Volume', value: `${Math.round(totalVolume).toLocaleString()} kg` },
    ];

    const gridY = 185;
    stats.forEach((stat, i) => {
      const col = i % 2;
      const row = Math.floor(i / 2);
      const x = col === 0 ? W / 4 : (3 * W) / 4;
      const y = gridY + row * 65;

      ctx.fillStyle = '#2ecc71';
      ctx.font = 'bold 28px "Bebas Neue", sans-serif';
      ctx.textAlign = 'center';
      ctx.fillText(stat.value, x, y);

      ctx.fillStyle = '#8a8a8a';
      ctx.font = '11px "Barlow Condensed", sans-serif';
      ctx.fillText(stat.label.toUpperCase(), x, y + 18);
    });

    // Exercise list
    let listY = gridY + 155;
    ctx.textAlign = 'left';

    ctx.fillStyle = '#8a8a8a';
    ctx.font = '10px "Barlow Condensed", sans-serif';
    ctx.fillText('EXERCISES', 40, listY);
    listY += 18;

    for (const ex of workout.exercises.slice(0, 8)) {
      const vol = ex.sets.reduce((a, s) => a + s.reps * s.weight, 0);

      ctx.fillStyle = '#e0e0e0';
      ctx.font = '14px "Barlow", sans-serif';
      ctx.fillText(ex.name, 40, listY);

      ctx.fillStyle = '#2ecc71';
      ctx.font = '12px "DM Mono", monospace';
      ctx.textAlign = 'right';
      ctx.fillText(`${ex.sets.length}s · ${Math.round(vol)}kg`, W - 40, listY);
      ctx.textAlign = 'left';

      listY += 24;
    }

    // Muscles worked
    if (muscles.length > 0) {
      listY += 10;
      ctx.fillStyle = '#8a8a8a';
      ctx.font = '10px "Barlow Condensed", sans-serif';
      ctx.fillText('MUSCLES WORKED', 40, listY);
      listY += 18;

      ctx.fillStyle = '#2ecc71';
      ctx.font = '13px "Barlow", sans-serif';
      ctx.fillText(muscles.join(' · '), 40, listY);
    }

    // Footer
    ctx.fillStyle = '#1a2e1f';
    ctx.font = '10px "Barlow", sans-serif';
    ctx.textAlign = 'center';
    ctx.fillText('Generated by FORGE — Gym OS', W / 2, H - 30);

    setDataUrl(canvas.toDataURL('image/png'));
  }, [workout]);

  useEffect(() => {
    if (open && workout) {
      // Small delay to ensure canvas is mounted
      setTimeout(drawPoster, 50);
    }
  }, [open, workout, drawPoster]);

  const handleDownload = () => {
    if (!dataUrl) return;
    const a = document.createElement('a');
    a.href = dataUrl;
    a.download = `forge-session-${new Date().toISOString().slice(0, 10)}.png`;
    a.click();
  };

  const handleShare = async () => {
    if (!dataUrl) return;
    try {
      const blob = await (await fetch(dataUrl)).blob();
      const file = new File([blob], 'forge-session.png', { type: 'image/png' });
      if (navigator.share) {
        await navigator.share({ files: [file], title: 'FORGE Session', text: 'Check out my workout!' });
      } else {
        handleDownload();
      }
    } catch {
      handleDownload();
    }
  };

  return (
    <Modal open={open} onClose={onClose} title="Session Poster">
      <div className="space-y-3">
        <canvas
          ref={canvasRef}
          className="w-full rounded-lg border border-forge-border"
          style={{ aspectRatio: '540/720' }}
        />
        <div className="flex gap-2">
          <button
            onClick={handleDownload}
            className="flex-1 bg-forge-green text-forge-bg py-2.5 rounded-lg font-condensed font-semibold text-sm"
          >
            Download
          </button>
          <button
            onClick={handleShare}
            className="flex-1 bg-forge-surface text-forge-text border border-forge-border py-2.5 rounded-lg font-condensed text-sm"
          >
            Share
          </button>
        </div>
      </div>
    </Modal>
  );
}
