export { WorkoutHistory } from './components/WorkoutHistory';
export { DashboardSection } from './components/DashboardSection';
export { VolumeChart } from './components/VolumeChart';
export { FreqChart } from './components/FreqChart';
export { BalanceChart } from './components/BalanceChart';
export { WeightChart } from './components/WeightChart';
export { MuscleHeatmap } from './components/MuscleHeatmap';
export { PRBoard } from './components/PRBoard';
export { ExerciseProgressionCard } from './components/ExerciseProgressionCard';
